//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ws.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public client()
        {
            this.order = new HashSet<order>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<int> isActive { get; set; }
        public string title { get; set; }
        public string note { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public int contactID { get; set; }
        public int addressID { get; set; }
    
        public virtual address address { get; set; }
        public virtual contact contact { get; set; }
        public virtual ICollection<order> order { get; set; }
    }
}
