//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ws.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment
    {
        public payment()
        {
            this.order = new HashSet<order>();
            this.paymentdetail = new HashSet<paymentdetail>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<float> price { get; set; }
        public Nullable<System.DateTime> paymentDate { get; set; }
        public Nullable<int> paymentType { get; set; }
        public Nullable<int> remainPrice { get; set; }
    
        public virtual ICollection<order> order { get; set; }
        public virtual ICollection<paymentdetail> paymentdetail { get; set; }
    }
}
