//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ws.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class paymentdetail
    {
        public int id { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<System.DateTime> updateDate { get; set; }
        public Nullable<int> isActive { get; set; }
        public Nullable<float> oldPrice { get; set; }
        public Nullable<float> newPrice { get; set; }
        public Nullable<float> paidAmount { get; set; }
        public int paymentID { get; set; }
    
        public virtual payment payment { get; set; }
    }
}
