//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testProject.Yetkiler {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KullaniciYetkiBilgisi", Namespace="http://schemas.datacontract.org/2004/07/YetkiKontrol.WCF.DataType")]
    [System.SerializableAttribute()]
    public partial class KullaniciYetkiBilgisi : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdSoyadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GumrukAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GumrukIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GumrukKoduField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HataMesajiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SicilNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TCKimlikNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VergiNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private testProject.Yetkiler.Yetki[] YetkiListesiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdSoyad {
            get {
                return this.AdSoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.AdSoyadField, value) != true)) {
                    this.AdSoyadField = value;
                    this.RaisePropertyChanged("AdSoyad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GumrukAdi {
            get {
                return this.GumrukAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.GumrukAdiField, value) != true)) {
                    this.GumrukAdiField = value;
                    this.RaisePropertyChanged("GumrukAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GumrukId {
            get {
                return this.GumrukIdField;
            }
            set {
                if ((object.ReferenceEquals(this.GumrukIdField, value) != true)) {
                    this.GumrukIdField = value;
                    this.RaisePropertyChanged("GumrukId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GumrukKodu {
            get {
                return this.GumrukKoduField;
            }
            set {
                if ((object.ReferenceEquals(this.GumrukKoduField, value) != true)) {
                    this.GumrukKoduField = value;
                    this.RaisePropertyChanged("GumrukKodu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HataMesaji {
            get {
                return this.HataMesajiField;
            }
            set {
                if ((object.ReferenceEquals(this.HataMesajiField, value) != true)) {
                    this.HataMesajiField = value;
                    this.RaisePropertyChanged("HataMesaji");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SicilNo {
            get {
                return this.SicilNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SicilNoField, value) != true)) {
                    this.SicilNoField = value;
                    this.RaisePropertyChanged("SicilNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TCKimlikNo {
            get {
                return this.TCKimlikNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TCKimlikNoField, value) != true)) {
                    this.TCKimlikNoField = value;
                    this.RaisePropertyChanged("TCKimlikNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VergiNo {
            get {
                return this.VergiNoField;
            }
            set {
                if ((object.ReferenceEquals(this.VergiNoField, value) != true)) {
                    this.VergiNoField = value;
                    this.RaisePropertyChanged("VergiNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public testProject.Yetkiler.Yetki[] YetkiListesi {
            get {
                return this.YetkiListesiField;
            }
            set {
                if ((object.ReferenceEquals(this.YetkiListesiField, value) != true)) {
                    this.YetkiListesiField = value;
                    this.RaisePropertyChanged("YetkiListesi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Yetki", Namespace="http://schemas.datacontract.org/2004/07/YetkiKontrol.WCF.DataType")]
    [System.SerializableAttribute()]
    public partial class Yetki : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirmaVergiNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YetkiAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YetkiIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YetkiPrefixField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirmaVergiNo {
            get {
                return this.FirmaVergiNoField;
            }
            set {
                if ((object.ReferenceEquals(this.FirmaVergiNoField, value) != true)) {
                    this.FirmaVergiNoField = value;
                    this.RaisePropertyChanged("FirmaVergiNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YetkiAdi {
            get {
                return this.YetkiAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.YetkiAdiField, value) != true)) {
                    this.YetkiAdiField = value;
                    this.RaisePropertyChanged("YetkiAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YetkiId {
            get {
                return this.YetkiIdField;
            }
            set {
                if ((this.YetkiIdField.Equals(value) != true)) {
                    this.YetkiIdField = value;
                    this.RaisePropertyChanged("YetkiId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YetkiPrefix {
            get {
                return this.YetkiPrefixField;
            }
            set {
                if ((object.ReferenceEquals(this.YetkiPrefixField, value) != true)) {
                    this.YetkiPrefixField = value;
                    this.RaisePropertyChanged("YetkiPrefix");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://gumruk.gov.tr/", ConfigurationName="Yetkiler.IYetkiService")]
    public interface IYetkiService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gumruk.gov.tr/IYetkiService/ProjeProfilListesi", ReplyAction="http://gumruk.gov.tr/IYetkiService/ProjeProfilListesiResponse")]
        string ProjeProfilListesi(int projeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gumruk.gov.tr/IYetkiService/KullaniciYetkileriniGetir", ReplyAction="http://gumruk.gov.tr/IYetkiService/KullaniciYetkileriniGetirResponse")]
        testProject.Yetkiler.KullaniciYetkiBilgisi KullaniciYetkileriniGetir(string tcno, string sifre, bool memurMu, string projeId, string ipAdresi, string macAdresi, string projeAdi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://gumruk.gov.tr/IYetkiService/KullaniciYetkileriDataSetXML", ReplyAction="http://gumruk.gov.tr/IYetkiService/KullaniciYetkileriDataSetXMLResponse")]
        string KullaniciYetkileriDataSetXML(string tcno, string sifre, bool memurMu);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IYetkiServiceChannel : testProject.Yetkiler.IYetkiService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class YetkiServiceClient : System.ServiceModel.ClientBase<testProject.Yetkiler.IYetkiService>, testProject.Yetkiler.IYetkiService {
        
        public YetkiServiceClient() {
        }
        
        public YetkiServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public YetkiServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public YetkiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public YetkiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ProjeProfilListesi(int projeId) {
            return base.Channel.ProjeProfilListesi(projeId);
        }
        
        public testProject.Yetkiler.KullaniciYetkiBilgisi KullaniciYetkileriniGetir(string tcno, string sifre, bool memurMu, string projeId, string ipAdresi, string macAdresi, string projeAdi) {
            return base.Channel.KullaniciYetkileriniGetir(tcno, sifre, memurMu, projeId, ipAdresi, macAdresi, projeAdi);
        }
        
        public string KullaniciYetkileriDataSetXML(string tcno, string sifre, bool memurMu) {
            return base.Channel.KullaniciYetkileriDataSetXML(tcno, sifre, memurMu);
        }
    }
}
